name: Build and Publish image to hub.opensciencegrid.org

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag condor_usage_metrics:latest
    - name: push image to osg hub
      run: |
        docker login -u clundst -p ${{ secrets.OSG_HUB_TOKEN }}
        docker push hub.opensciencegrid.org/coffea-casa/condor_usage_metrics:latest
    
